/*
Copyright 2025 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
	v1 "k8s.io/ingress-gce/pkg/apis/negbinding/v1"
	scheme "k8s.io/ingress-gce/pkg/negbinding/clientset/versioned/scheme"
)

// NetworkEndpointGroupBindingsGetter has a method to return a NetworkEndpointGroupBindingInterface.
// A group's client should implement this interface.
type NetworkEndpointGroupBindingsGetter interface {
	NetworkEndpointGroupBindings(namespace string) NetworkEndpointGroupBindingInterface
}

// NetworkEndpointGroupBindingInterface has methods to work with NetworkEndpointGroupBinding resources.
type NetworkEndpointGroupBindingInterface interface {
	Create(ctx context.Context, networkEndpointGroupBinding *v1.NetworkEndpointGroupBinding, opts metav1.CreateOptions) (*v1.NetworkEndpointGroupBinding, error)
	Update(ctx context.Context, networkEndpointGroupBinding *v1.NetworkEndpointGroupBinding, opts metav1.UpdateOptions) (*v1.NetworkEndpointGroupBinding, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, networkEndpointGroupBinding *v1.NetworkEndpointGroupBinding, opts metav1.UpdateOptions) (*v1.NetworkEndpointGroupBinding, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.NetworkEndpointGroupBinding, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.NetworkEndpointGroupBindingList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.NetworkEndpointGroupBinding, err error)
	NetworkEndpointGroupBindingExpansion
}

// networkEndpointGroupBindings implements NetworkEndpointGroupBindingInterface
type networkEndpointGroupBindings struct {
	*gentype.ClientWithList[*v1.NetworkEndpointGroupBinding, *v1.NetworkEndpointGroupBindingList]
}

// newNetworkEndpointGroupBindings returns a NetworkEndpointGroupBindings
func newNetworkEndpointGroupBindings(c *K8sV1Client, namespace string) *networkEndpointGroupBindings {
	return &networkEndpointGroupBindings{
		gentype.NewClientWithList[*v1.NetworkEndpointGroupBinding, *v1.NetworkEndpointGroupBindingList](
			"networkendpointgroupbindings",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *v1.NetworkEndpointGroupBinding { return &v1.NetworkEndpointGroupBinding{} },
			func() *v1.NetworkEndpointGroupBindingList { return &v1.NetworkEndpointGroupBindingList{} }),
	}
}
