/*
Copyright 2025 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1 "k8s.io/ingress-gce/pkg/apis/negbinding/v1"
)

// FakeNetworkEndpointGroupBindings implements NetworkEndpointGroupBindingInterface
type FakeNetworkEndpointGroupBindings struct {
	Fake *FakeK8sV1
	ns   string
}

var networkendpointgroupbindingsResource = v1.SchemeGroupVersion.WithResource("networkendpointgroupbindings")

var networkendpointgroupbindingsKind = v1.SchemeGroupVersion.WithKind("NetworkEndpointGroupBinding")

// Get takes name of the networkEndpointGroupBinding, and returns the corresponding networkEndpointGroupBinding object, and an error if there is any.
func (c *FakeNetworkEndpointGroupBindings) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.NetworkEndpointGroupBinding, err error) {
	emptyResult := &v1.NetworkEndpointGroupBinding{}
	obj, err := c.Fake.
		Invokes(testing.NewGetActionWithOptions(networkendpointgroupbindingsResource, c.ns, name, options), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1.NetworkEndpointGroupBinding), err
}

// List takes label and field selectors, and returns the list of NetworkEndpointGroupBindings that match those selectors.
func (c *FakeNetworkEndpointGroupBindings) List(ctx context.Context, opts metav1.ListOptions) (result *v1.NetworkEndpointGroupBindingList, err error) {
	emptyResult := &v1.NetworkEndpointGroupBindingList{}
	obj, err := c.Fake.
		Invokes(testing.NewListActionWithOptions(networkendpointgroupbindingsResource, networkendpointgroupbindingsKind, c.ns, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1.NetworkEndpointGroupBindingList{ListMeta: obj.(*v1.NetworkEndpointGroupBindingList).ListMeta}
	for _, item := range obj.(*v1.NetworkEndpointGroupBindingList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested networkEndpointGroupBindings.
func (c *FakeNetworkEndpointGroupBindings) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchActionWithOptions(networkendpointgroupbindingsResource, c.ns, opts))

}

// Create takes the representation of a networkEndpointGroupBinding and creates it.  Returns the server's representation of the networkEndpointGroupBinding, and an error, if there is any.
func (c *FakeNetworkEndpointGroupBindings) Create(ctx context.Context, networkEndpointGroupBinding *v1.NetworkEndpointGroupBinding, opts metav1.CreateOptions) (result *v1.NetworkEndpointGroupBinding, err error) {
	emptyResult := &v1.NetworkEndpointGroupBinding{}
	obj, err := c.Fake.
		Invokes(testing.NewCreateActionWithOptions(networkendpointgroupbindingsResource, c.ns, networkEndpointGroupBinding, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1.NetworkEndpointGroupBinding), err
}

// Update takes the representation of a networkEndpointGroupBinding and updates it. Returns the server's representation of the networkEndpointGroupBinding, and an error, if there is any.
func (c *FakeNetworkEndpointGroupBindings) Update(ctx context.Context, networkEndpointGroupBinding *v1.NetworkEndpointGroupBinding, opts metav1.UpdateOptions) (result *v1.NetworkEndpointGroupBinding, err error) {
	emptyResult := &v1.NetworkEndpointGroupBinding{}
	obj, err := c.Fake.
		Invokes(testing.NewUpdateActionWithOptions(networkendpointgroupbindingsResource, c.ns, networkEndpointGroupBinding, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1.NetworkEndpointGroupBinding), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeNetworkEndpointGroupBindings) UpdateStatus(ctx context.Context, networkEndpointGroupBinding *v1.NetworkEndpointGroupBinding, opts metav1.UpdateOptions) (result *v1.NetworkEndpointGroupBinding, err error) {
	emptyResult := &v1.NetworkEndpointGroupBinding{}
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceActionWithOptions(networkendpointgroupbindingsResource, "status", c.ns, networkEndpointGroupBinding, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1.NetworkEndpointGroupBinding), err
}

// Delete takes name of the networkEndpointGroupBinding and deletes it. Returns an error if one occurs.
func (c *FakeNetworkEndpointGroupBindings) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(networkendpointgroupbindingsResource, c.ns, name, opts), &v1.NetworkEndpointGroupBinding{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeNetworkEndpointGroupBindings) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	action := testing.NewDeleteCollectionActionWithOptions(networkendpointgroupbindingsResource, c.ns, opts, listOpts)

	_, err := c.Fake.Invokes(action, &v1.NetworkEndpointGroupBindingList{})
	return err
}

// Patch applies the patch and returns the patched networkEndpointGroupBinding.
func (c *FakeNetworkEndpointGroupBindings) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.NetworkEndpointGroupBinding, err error) {
	emptyResult := &v1.NetworkEndpointGroupBinding{}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceActionWithOptions(networkendpointgroupbindingsResource, c.ns, name, pt, data, opts, subresources...), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1.NetworkEndpointGroupBinding), err
}
