/*
Copyright 2025 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/listers"
	"k8s.io/client-go/tools/cache"
	v1 "k8s.io/ingress-gce/pkg/apis/negbinding/v1"
)

// NetworkEndpointGroupBindingLister helps list NetworkEndpointGroupBindings.
// All objects returned here must be treated as read-only.
type NetworkEndpointGroupBindingLister interface {
	// List lists all NetworkEndpointGroupBindings in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1.NetworkEndpointGroupBinding, err error)
	// NetworkEndpointGroupBindings returns an object that can list and get NetworkEndpointGroupBindings.
	NetworkEndpointGroupBindings(namespace string) NetworkEndpointGroupBindingNamespaceLister
	NetworkEndpointGroupBindingListerExpansion
}

// networkEndpointGroupBindingLister implements the NetworkEndpointGroupBindingLister interface.
type networkEndpointGroupBindingLister struct {
	listers.ResourceIndexer[*v1.NetworkEndpointGroupBinding]
}

// NewNetworkEndpointGroupBindingLister returns a new NetworkEndpointGroupBindingLister.
func NewNetworkEndpointGroupBindingLister(indexer cache.Indexer) NetworkEndpointGroupBindingLister {
	return &networkEndpointGroupBindingLister{listers.New[*v1.NetworkEndpointGroupBinding](indexer, v1.Resource("networkendpointgroupbinding"))}
}

// NetworkEndpointGroupBindings returns an object that can list and get NetworkEndpointGroupBindings.
func (s *networkEndpointGroupBindingLister) NetworkEndpointGroupBindings(namespace string) NetworkEndpointGroupBindingNamespaceLister {
	return networkEndpointGroupBindingNamespaceLister{listers.NewNamespaced[*v1.NetworkEndpointGroupBinding](s.ResourceIndexer, namespace)}
}

// NetworkEndpointGroupBindingNamespaceLister helps list and get NetworkEndpointGroupBindings.
// All objects returned here must be treated as read-only.
type NetworkEndpointGroupBindingNamespaceLister interface {
	// List lists all NetworkEndpointGroupBindings in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1.NetworkEndpointGroupBinding, err error)
	// Get retrieves the NetworkEndpointGroupBinding from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1.NetworkEndpointGroupBinding, error)
	NetworkEndpointGroupBindingNamespaceListerExpansion
}

// networkEndpointGroupBindingNamespaceLister implements the NetworkEndpointGroupBindingNamespaceLister
// interface.
type networkEndpointGroupBindingNamespaceLister struct {
	listers.ResourceIndexer[*v1.NetworkEndpointGroupBinding]
}
